#references:
#  - C.C. Tasan et al.,
#    Acta Materialia 81:386-400, 2014,
#    https://doi.org/10.1016/j.actamat.2014.07.071
#  - U.F. Kocks,
#   Metallurgical and Materials Transactions B 1:1121–1143, 1970,
#    https://doi.org/10.1007/BF02900224

Ferrite:
  lattice: cI
  mechanical:
    output: [F,F_e,F_p,P,L_p,O]
    elastic: {C_11: 233.3e9, C_12: 135.5e9, C_44: 118.0e9, type: Hooke}
    plastic:
      output: [xi_sl,gamma_sl]
      N_sl: [12, 12]
      a_sl: 2.0
      dot_gamma_0_sl: 0.001
      h_0_sl-sl: 1000.0e6
      h_sl-sl: [1, 1.4, 1, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4]
      n_sl: 20
      type: phenopowerlaw
      xi_0_sl: [95.e6, 96.e6]
      xi_inf_sl: [222.e6, 412.7e6]
Martensite:
  lattice: cI
  mechanical:
    output: [F,F_e,F_p,P,L_p,O]
    elastic: {C_11: 417.4e9, C_12: 242.4e9, C_44: 211.1e9, type: Hooke}
    plastic:
      output: [xi_sl,gamma_sl]
      N_sl: [12, 12]
      a_sl: 2.0
      dot_gamma_0_sl: 0.001
      h_0_sl-sl: 563.0e9
      h_sl-sl: [1, 1.4, 1, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4]
      n_sl: 20
      type: phenopowerlaw
      xi_0_sl: [405.8e6, 456.7e6]
      xi_inf_sl: [872.9e6, 971.2e6]
